# Generated by Django 4.0.6 on 2022-07-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_post_alter_like_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('DR', 'Draft'), ('PUB', 'Published')], default='PUB', max_length=3, null=True),
        ),
    ]
